# Generated by Django 2.2b1 on 2019-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('field', models.IntegerField(choices=[(0, 'Mobile Development'), (1, 'Web Development'), (2, 'Web Design'), (3, 'Enterprise'), (4, 'Financial Learning'), (5, 'Basic Programming')])),
                ('description', models.TextField()),
                ('intro_video', models.URLField(verbose_name='course introduction youtube link')),
                ('price', models.FloatField(default=0.0)),
                ('rating', models.FloatField()),
                ('videos_num', models.IntegerField()),
                ('videos_Time', models.IntegerField(verbose_name='total videos Time by minutes')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.BooleanField(choices=[(False, 'Male'), (True, 'Female')]),
        ),
    ]
