# Generated by Django 2.2b1 on 2019-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_auto_20190601_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.FloatField(default=0.0, help_text='with dollars $'),
        ),
    ]
