# Generated by Django 2.2b1 on 2019-06-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20190601_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='intro_video',
            field=models.URLField(help_text='youtube link', verbose_name='introduction video'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='rating',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='videos_Time',
            field=models.IntegerField(help_text=' in minutes', verbose_name='total videos Time'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('host', models.IntegerField()),
                ('link', models.URLField()),
                ('desc', models.TextField(verbose_name='Description')),
                ('attachment', models.FileField(null=True, upload_to='pdf/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Link_Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('link_String', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Video')),
            ],
        ),
    ]
