# Generated by Django 2.2b1 on 2019-06-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_auto_20190604_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='link',
            new_name='video_link',
        ),
        migrations.AddField(
            model_name='video',
            name='link1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link_String1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='link_String2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Link_Sharing',
        ),
    ]
