# Generated by Django 2.2b1 on 2019-06-04 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course', '0005_auto_20190604_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='host',
            field=models.IntegerField(choices=[(0, 'You Tube'), (1, 'Vimeo'), (2, 'Dailymotion'), (3, 'Jetpack'), (4, 'Wistia'), (5, 'Vidyard')]),
        ),
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enroll', models.BooleanField(default=False)),
                ('paid', models.FloatField(default=0.0)),
                ('Progrss', models.IntegerField()),
                ('review_num', models.FloatField()),
                ('review', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('pic', models.ImageField(default=None, upload_to='post_pic/')),
                ('attachment', models.FileField(default=None, upload_to='post_doc/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Course.Courses')),
                ('replay_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Group')),
            ],
        ),
    ]
