# Generated by Django 2.2b1 on 2019-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20190604_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='post_doc/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pic',
            field=models.ImageField(blank=True, default=None, upload_to='post_pic/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link_String1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='link_String2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
