# Generated by Django 2.2b1 on 2019-06-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20190604_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='rating',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='replay_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Group'),
        ),
    ]
