# Generated by Django 2.2b1 on 2019-06-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20190604_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pic', models.ImageField(blank=True, default=None, upload_to='post_pic/')),
                ('attachment', models.FileField(blank=True, default=None, upload_to='post_doc/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Courses')),
                ('replay_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
